# Generated by Django 3.0.5 on 2020-04-27 06:21

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Guitar')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Guitar Address')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('genre', models.CharField(choices=[('generic', 'Generic'), ('blues', 'Blues'), ('soul', 'Soul'), ('jazz', 'Jazz'), ('hard-rock', 'Hard-Rock'), ('pop', 'Pop')], default='generic', max_length=20, verbose_name='Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
